### ISSUE TITLE
pointsOfWinner not sync with points of winner

### ISSUE THREAD

**Issue by coderbradlee** [Certora/tutorials-code#25]
A run of the new BordaMissingRule.spec on the original Borda.sol that is verified
https://prover.certora.com/output/738862/2cc3abb2da82413ca269ee65d7b29d0a?anonymousKey=c0979cf572194bb4629657192c849ba54d61c6fc
I am not sure about this one,maybe it's Certora's bug?Because there's no place to set pointsOfWinner

A run of Borda.spec on BordaNewBug.sol showing the existing spec misses the bug
https://prover.certora.com/output/738862/82ed220f31a2486c9db0822b8f142a9b?anonymousKey=f7312a8b2f71bb5d4b3ea84c54d1ca13887082eb

A run of BordaMissingRule.spec on BordaNewBug.sol showing your rule catches the bug
https://prover.certora.com/output/738862/398479f4d55846dfb15357b979df22ca?anonymousKey=8af8a5216248987b9d413ffcff06463941faee87

pr is this https://github.com/Certora/tutorials-code/pull/24

**Comment by Czar102** [comment]
The verification in the first link fails because the rule does not require the invariant that the `pointsOfWinner` is always zero. So it assumed otherwise and that variable was different than the actual number of points of winner.
To fix, you could make the rule an invariant:
```
//pointsOfWinner should be 0 in original Borda.sol 
//pointsOfWinner should be winner's point
invariant BordaMissingRule()
    pointsOfWinner() == 0 || pointsOfWinner() == points(winner());
```
The failure on the `BordaNewBug.sol` is also a result of this phenomena. The above invariant should succeed as well.

**Comment by coderbradlee** [comment]
> The verification in the first link fails because the rule does not require the invariant that the `pointsOfWinner` is always zero. So it assumed otherwise and that variable was different than the actual number of points of winner. To fix, you could make the rule an invariant:
> 
> ```
> //pointsOfWinner should be 0 in original Borda.sol 
> //pointsOfWinner should be winner's point
> invariant BordaMissingRule()
>     pointsOfWinner() == 0 || pointsOfWinner() == points(winner());
> ```
> 
> The failure on the `BordaNewBug.sol` is also a result of this phenomena. The above invariant should succeed as well.

https://prover.certora.com/output/49230/38beae32cad8478f956013660e083a20?anonymousKey=c7fa33a5c5ffcc971369852c4832726a5ba1f3e8 invariant have same error

**Comment by coderbradlee** [comment]
https://prover.certora.com/output/49230/3f832dee6e634a2282ffeb0f6ac200f0?anonymousKey=c53bde1199f2895d28fa3faae637ceabc02c38d1  add 
    require(pointsOfWinner()==0); is good

**Comment by coderbradlee** [comment]
rule BordaMissingRule(address f, address s, address t) {
    env e;
    require(pointsOfWinner()==0);
    vote(e, f, s, t);
    assert (pointsOfWinner()==0)||(pointsOfWinner() == points(winner())),   "unexpected change of points";
} cannot find the bug

**Comment by coderbradlee** [comment]
https://prover.certora.com/output/49230/046df117972f4b8582af3a0124c0461c?anonymousKey=88c7608340b422a9157afaedaf1e6413d39225de 
use this rule:
rule BordaMissingRule(address f, address s, address t) {
    env e;
    require(pointsOfWinner()==0);
    vote(e, f, s, t);
    assert (pointsOfWinner()==0)||(pointsOfWinner() == points(winner())),   "unexpected change of points";
}

can't find the bug,I don't understand
